"""Init DB and tables

Revision ID: b704bd9c6061
Revises: Tomáš Macko
Create Date: 2022-12-03 23:17:45.705374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b704bd9c6061'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('country', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)

    op.create_table('kennels',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('club_id', sa.Integer(), nullable=True),
                    sa.Column('origin_date', sa.Date(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_kennels_id'), 'kennels', ['id'], unique=False)

    op.create_table('dogs',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('kennel_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('price_amount', sa.Float(), nullable=True),
                    sa.Column('price_currency', sa.String(), nullable=True),
                    sa.Column('gender', sa.String(), nullable=False),
                    sa.Column('dob', sa.Date(), nullable=False),
                    sa.ForeignKeyConstraint(['kennel_id'], ['kennels.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('parents',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('self_id', postgresql.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['self_id'], ['dogs.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('litters',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('dogs_count', sa.Integer(), nullable=False),
                    sa.Column('order_letter', sa.String(), nullable=False),
                    sa.Column('dob', sa.Date(), nullable=False),
                    sa.Column('mother_id', postgresql.UUID(), nullable=False),
                    sa.Column('father_id', postgresql.UUID(), nullable=False),
                    sa.Column('kennel_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['father_id'], ['parents.id'], ),
                    sa.ForeignKeyConstraint(['kennel_id'], ['kennels.id'], ),
                    sa.ForeignKeyConstraint(['mother_id'], ['parents.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_litters_id'), 'litters', ['id'], unique=False)

    op.add_column(
        'dogs',
        sa.Column('litter_id', sa.Integer(),  sa.ForeignKey('litters.id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kennels_id'), table_name='kennels')
    op.drop_table('kennels')
    op.drop_table('parents')
    op.drop_index(op.f('ix_litters_id'), table_name='litters')
    op.drop_table('litters')
    op.drop_table('dogs')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_table('clubs')
    # ### end Alembic commands ###
